apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kedify-http:admin
rules:
- apiGroups: ["http.keda.sh"]
  resources: ["httpscaledobjects"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kedify-http-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda
roleRef:
  kind: ClusterRole
  name: kedify-http:admin
  apiGroup: rbac.authorization.k8s.io
